### ISSUE TITLE
Spilo Endpoint updates force constant resyncs of ipvs

### ISSUE THREAD

**Issue by Thoro** [cloudnativelabs/kube-router#1026]
**What happened?**
I'm running Spilo in my cluster, which updates annotation on the endpoints object:

```
 annotations:
    acquireTime: "2021-01-21T11:18:59.523373+00:00"
    leader: harbor-db-0
    optime: "158075120872"
    renewTime: "2021-01-25T09:58:10.851366+00:00"
    transitions: "7"
    ttl: "30"
```

Thos annotations are updated every 5 - 10 seconds which force a full ipvs resync (which takes ~500ms) this leads to a high load from the kube-router process (50 - 80% of one core)

**What did you expect to happen?**
Changes that don't affect the ipvs tables should not trigger a resync.

**How can we reproduce the behavior you experienced?**
Have a bunch of service and update an annotation of the endpoints object, each update triggers a ipvs resync

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): v1.1.1 (after upgrade from ancient 0.2.5)
 - Kube-Router Parameters: [e.g. --run-router --run-service-proxy --enable-overlay --overlay-type=full etc.]:
 ```
        - "--run-router=false"
        - "--run-firewall=true"
        - "--enable-overlay=false"
        - "--run-service-proxy=true"
        - "--ipvs-sync-period=1m"
        - "--masquerade-all=true"
        - "--enable-pod-egress=false"
        - "--kubeconfig=/var/lib/kube-router/kubeconfig"
        - "--enable-cni=false"
        - "--metrics-port=8080"
        - "--metrics-path=/metrics"
        - "-v=2"
```
 - Kubernetes Version (`kubectl version`) : [e.g. 1.18.3] 1.17.17 (in the process of updating to 1.20)
 - Cloud Type: [e.g. AWS, GCP, Azure, on premise] on premise
 - Kubernetes Deployment Type: [e.g. EKS, GKE, Kops, Kubeadm, etc.] manual
 - Kube-Router Deployment Type: [e.g. DaemonSet, System Service] DaemonSet
 - Cluster Size: [e.g. 200 Nodes] 34 nodes

![Screenshot 2021-01-25 at 11 17 11](https://user-images.githubusercontent.com/554474/105692671-faf50d80-5efe-11eb-9141-b377f37fe7cd.png)
