### ISSUE TITLE
Kube-router mixes iptables-legacy and iptables-nft rules

### ISSUE THREAD

**Issue by akamac** [cloudnativelabs/kube-router#1069]
**What happened?**
Traffic does not go through `kube-bridge` as it is dropped by iptables. Hence, no connectivity between pods even on the same node.

**How can we reproduce the behavior you experienced?**
```
      initContainers:
      - name: install-cni
        image: &image docker.io/cloudnativelabs/kube-router:v1.2.1
        command:
        - cp
        args:
        - -f
        - /etc/kube-router/cni-conf.json
        - /etc/cni/net.d/00-kuberouter.conflist
        volumeMounts:
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d/
        - name: kube-router-cfg
          mountPath: /etc/kube-router/
      containers:
      - name: kube-router
        image: *image
        args:
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --hairpin-mode=true
#        - --bgp-graceful-restart=true
        - --enable-cni=true
        - --enable-ibgp=true
        - --enable-overlay=false
        - --service-cluster-ip-range={{ service_subnet }}
        - --enable-pod-egress=true  # default: true
        - --peer-router-ips={{ bgp.peer_router_ip }}
        - --peer-router-asns={{ bgp.peer_router_asn }}
        - --cluster-asn={{ bgp.cluster_asn }}
        - --advertise-cluster-ip=false
        - --advertise-external-ip=false  # use service annotations
        - --advertise-loadbalancer-ip=false
        - --advertise-pod-cidr=true
        - --metrics-port=20245
        - --nodes-full-mesh=false
        - --kubeconfig=/var/lib/kube-router/kubeconfig.conf
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_ROUTER_CNI_CONF_FILE
          value: /etc/cni/net.d/00-kuberouter.conflist
        livenessProbe:
          httpGet:
            path: /healthz
            port: 20244
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules/
          readOnly: true
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d/
        - name: kube-router-cfg
          mountPath: /var/lib/kube-router/
          readOnly: true
        - name: xtables-lock
          mountPath: /run/xtables.lock
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules/
      - name: cni-conf-dir
        hostPath:
          path: /etc/cni/net.d/
      - name: kube-router-cfg
        configMap:
          name: kube-router-cfg
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
```
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-router-cfg
  namespace: kube-system
  labels:
    app: kube-router
    tier: node
data:
  cni-conf.json: |
    {
      "cniVersion": "0.3.1",
      "name": "mynet",
      "plugins": [
        {
          "name": "kubernetes",
          "type": "bridge",
          "bridge": "kube-bridge",
          "isDefaultGateway": true,
          "ipam": {
            "type": "host-local"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {
            "portMappings": true
          }
        },
        {
          "type": "bandwidth",
          "capabilities": {
            "bandwidth": true
          }
        }
      ]
    }
  kubeconfig.conf: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://{{ api_server_fqdn }}:{{ api_server_port }}
      name: cluster
    contexts:
    - context:
        cluster: cluster
        namespace: kube-system
        user: kube-router
      name: kube-router-context
    current-context: kube-router-context
    users:
    - name: kube-router
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```
`iptables-save`:
```
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-KUBELET-CANARY - [0:0]
-A INPUT -j KUBE-FIREWALL
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
-A KUBE-FIREWALL -m mark --mark 0x8000/0x8000 -m comment --comment "kubernetes firewall for dropping marked packets" -j DROP
-A KUBE-FIREWALL ! -s 127.0.0.0/8 -d 127.0.0.0/8 -m conntrack ! --ctstate RELATED,ESTABLISHED,DNAT -m comment --comment "block incoming localnet connections" -j DROP
COMMIT
# Completed on Thu Apr 15 10:50:41 2021
# Generated by xtables-save v1.8.2 on Thu Apr 15 10:50:41 2021
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-KUBELET-CANARY - [0:0]
:CNI-HOSTPORT-SETMARK - [0:0]
:CNI-HOSTPORT-MASQ - [0:0]
:CNI-HOSTPORT-DNAT - [0:0]
:CNI-DN-4456bd675e1299ff44328 - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A PREROUTING -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A POSTROUTING -m comment --comment "CNI portfwd requiring masquerade" -j CNI-HOSTPORT-MASQ
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -o docker0 -m addrtype --src-type LOCAL -j MASQUERADE
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN
-A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
-A CNI-HOSTPORT-SETMARK -m comment --comment "CNI portfwd masquerade mark" -j MARK --set-xmark 0x2000/0x2000
-A CNI-HOSTPORT-MASQ -m mark --mark 0x2000/0x2000 -j MASQUERADE
-A CNI-HOSTPORT-DNAT -p tcp -m multiport --dports 80,443 -m comment --comment "dnat name: \"mynet\" id: \"e4baf9d0b9365bac4efaca5fa06c4e8d5694bcb9c7a25eec042c25c88de09bd7\"" -j CNI-DN-4456bd675e1299ff44328
-A CNI-DN-4456bd675e1299ff44328 -s 192.168.130.0/24 -p tcp -m tcp --dport 80 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-4456bd675e1299ff44328 -s 127.0.0.1/32 -p tcp -m tcp --dport 80 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-4456bd675e1299ff44328 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.130.32:80
-A CNI-DN-4456bd675e1299ff44328 -s 192.168.130.0/24 -p tcp -m tcp --dport 443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-4456bd675e1299ff44328 -s 127.0.0.1/32 -p tcp -m tcp --dport 443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-4456bd675e1299ff44328 -p tcp -m tcp --dport 443 -j DNAT --to-destination 192.168.130.32:443
COMMIT
# Completed on Thu Apr 15 10:50:41 2021
# Generated by xtables-save v1.8.2 on Thu Apr 15 10:50:41 2021
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:KUBE-KUBELET-CANARY - [0:0]
COMMIT
```
I expect also these rules to be present:
```
-A FORWARD -s 192.168.128.0/17 -j ACCEPT
-A FORWARD -d 192.168.128.0/17 -j ACCEPT
```

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 1.2.1
 - Kube-Router Parameters: see above
 - Kubernetes Version (`kubectl version`) : 1.18.13
 - Cloud Type: on premise
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 6 Nodes

**Container logs:**
```
I0415 10:50:32.402266       1 version.go:21] Running /usr/local/bin/kube-router version v1.2.1-dirty, built on 2021-04-01T11:26:43+0000, go1.15.8
I0415 10:50:32.507448       1 metrics_controller.go:175] Starting metrics controller
I0415 10:50:32.523839       1 network_routes_controller.go:1152] Could not find annotation `kube-router.io/bgp-local-addresses` on node object so BGP will listen on node IP: 10.226.73.12 address.
I0415 10:50:32.527680       1 network_routes_controller.go:351] `subnet` in CNI conf file is empty so populating `subnet` in CNI conf file with pod CIDR assigned to the node obtained from node spec.
I0415 10:50:32.626391       1 network_services_controller.go:294] Starting network services controller
I0415 10:50:32.628279       1 network_routes_controller.go:221] Setting MTU of kube-bridge interface to: 1500
I0415 10:50:32.630420       1 network_routes_controller.go:248] Starting network route controller
I0415 10:50:32.634744       1 network_routes_controller.go:794] Found ASN for the node to be 64551 from the node annotations
time="2021-04-15T10:50:32Z" level=info msg="Add a peer configuration for:10.226.73.1" Topic=Peer
time="2021-04-15T10:50:32Z" level=info msg="Add a peer configuration for:10.226.73.15" Topic=Peer
time="2021-04-15T10:50:32Z" level=info msg="Add a peer configuration for:10.226.73.16" Topic=Peer
time="2021-04-15T10:50:32Z" level=info msg="Add a peer configuration for:10.226.73.11" Topic=Peer
time="2021-04-15T10:50:32Z" level=info msg="Add a peer configuration for:10.226.73.13" Topic=Peer
time="2021-04-15T10:50:32Z" level=info msg="Add a peer configuration for:10.226.73.14" Topic=Peer
I0415 10:50:32.836654       1 network_policy_controller.go:142] Starting network policy controller
I0415 10:50:32.870923       1 network_policy_controller.go:150] Starting network policy controller full sync goroutine
time="2021-04-15T10:50:37Z" level=info msg="Peer Up" Key=10.226.73.14 State=BGP_FSM_OPENCONFIRM Topic=Peer
I0415 10:50:37.789745       1 network_routes_controller.go:543] Cleaning up old routes if there are any
I0415 10:50:37.790085       1 network_routes_controller.go:557] Cleaning up if there is any existing tunnel interface for the node
time="2021-04-15T10:50:38Z" level=info msg="Peer Up" Key=10.226.73.15 State=BGP_FSM_OPENCONFIRM Topic=Peer
time="2021-04-15T10:50:38Z" level=info msg="Peer Up" Key=10.226.73.13 State=BGP_FSM_OPENCONFIRM Topic=Peer
I0415 10:50:38.786774       1 network_routes_controller.go:543] Cleaning up old routes if there are any
I0415 10:50:38.787049       1 network_routes_controller.go:557] Cleaning up if there is any existing tunnel interface for the node
I0415 10:50:38.787320       1 network_routes_controller.go:543] Cleaning up old routes if there are any
I0415 10:50:38.787556       1 network_routes_controller.go:557] Cleaning up if there is any existing tunnel interface for the node
time="2021-04-15T10:50:39Z" level=info msg="Peer Up" Key=10.226.73.16 State=BGP_FSM_OPENCONFIRM Topic=Peer
I0415 10:50:39.719393       1 network_routes_controller.go:543] Cleaning up old routes if there are any
I0415 10:50:39.719727       1 network_routes_controller.go:557] Cleaning up if there is any existing tunnel interface for the node
time="2021-04-15T10:50:39Z" level=info msg="Peer Up" Key=10.226.73.11 State=BGP_FSM_OPENCONFIRM Topic=Peer
I0415 10:50:39.786895       1 network_routes_controller.go:543] Cleaning up old routes if there are any
I0415 10:50:39.787191       1 network_routes_controller.go:557] Cleaning up if there is any existing tunnel interface for the node
time="2021-04-15T10:50:49Z" level=info msg="Peer Up" Key=10.226.73.1 State=BGP_FSM_OPENCONFIRM Topic=Peer
```

**Comment by akamac** [comment]
As I see from the code, there should be
`-A FORWARD -m comment --comment "allow inbound traffic from pods" -i kube-bridge -j ACCEPT`
`-A FORWARD -m comment --comment "allow outbound traffic from pods" -o kube-bridge -j ACCEPT`
rules, but they are missing.
https://github.com/cloudnativelabs/kube-router/blob/ef827d3dbffeb9595120a90869a2ac616bd89e5f/pkg/controllers/routing/network_routes_controller.go#L745

**Comment by akamac** [comment]
They are actually present in `iptables-legacy`, while Debian Buster uses `iptables-nft` by default.

**Comment by akamac** [comment]
So https://github.com/cloudnativelabs/kube-router/pull/1061 should fix it, I guess. I'm pretty surprised I am the first who faced it.

**Comment by aauren** [comment]
@akamac we're still waiting on the overhaul of our build system to have a fix for ARM64 systems, which is why we haven't merged #1061 

However, assuming that you're not running ARM64 where you found this problem, can you try kube-router with that patch, either by building it yourself, or using the container that I built: `aauren/kube-router-git:514ea9c85` and see if that resolves the issue you're seeing? That would at least help us validate that our approach there works in the meantime.

**Comment by rkojedzinszky** [comment]
@aauren @akamac I have built kube-router based on #1061, is available at ghcr.io/rkojedzinszky/kube-router:latest. It works for me, now it uses iptables-nft binaries.

**Comment by ghglza** [comment]
@aauren so I finally managed to try your image with commit 514ea9c85 -- but it hangs on startup in the init container while trying to mount volumes not present in the daemonset [resource](https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter-all-features.yaml) we use.
Can you make your daemonset declaration available?

**Comment by aauren** [comment]
@ghglza So while I don't use the daemonset, I can't give you much feedback there. But it basically only has a host mount of `/etc/cni/net.d` and a mount of the config map that is declared earlier in the daemonset. Everything looks syntactically correct. I would need logs to know more about what's going on, but I don't think that its really necessary as @rkojedzinszky was already able to test the configuration and give me the feedback I was looking for.

**Comment by rkojedzinszky** [comment]
> @aauren so I finally managed to try your image with commit 514ea9c85 -- but it hangs on startup in the init container while trying to mount volumes not present in the daemonset [resource](https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter-all-features.yaml) we use.
> Can you make your daemonset declaration available?

my daemonset is:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-router
      tier: node
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2021-01-04T22:20:09+01:00"
      creationTimestamp: null
      labels:
        k8s-app: kube-router
        tier: node
    spec:
      containers:
      - args:
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --bgp-graceful-restart=true
        - --bgp-graceful-restart-deferral-time=30s
        - --advertise-external-ip=true
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KUBE_ROUTER_CNI_CONF_FILE
          value: /etc/cni/net.d/10-kuberouter.conflist
        image: ghcr.io/rkojedzinszky/kube-router:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 20244
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: kube-router
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /etc/cni/net.d
          name: cni-conf-dir
        - mountPath: /var/lib/kube-router
          name: kubeconfig
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command:
        - /bin/sh
        - -c
        - set -e -x; if [ ! -f /etc/cni/net.d/10-kuberouter.conflist ]; then if [
          -f /etc/cni/net.d/*.conf ]; then rm -f /etc/cni/net.d/*.conf; fi; TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
          cp /etc/kube-router/cni-conf.json ${TMP}; mv ${TMP} /etc/cni/net.d/10-kuberouter.conflist;
          fi
        image: docker.io/cloudnativelabs/kube-router:v1.2.2
        imagePullPolicy: IfNotPresent
        name: install-cni
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cni/net.d
          name: cni-conf-dir
        - mountPath: /etc/kube-router
          name: kube-router-cfg
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-router
      serviceAccountName: kube-router
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni-conf-dir
      - configMap:
          defaultMode: 420
          name: kube-router-cfg
        name: kube-router-cfg
      - configMap:
          defaultMode: 420
          items:
          - key: kubeconfig.conf
            path: kubeconfig
          name: kube-router-kubeconfig
        name: kubeconfig
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```
