### ISSUE TITLE
Egress NetworkPolicy to pods with host network is not working

### ISSUE THREAD

**Issue by paxnil** [cloudnativelabs/kube-router#1135]
**What happened?**
I have a rook ceph cluster deployed with host network.
And an egress network policy set as following.
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-s3
  namespace: gitlab-deploy
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: rook-ceph
      podSelector:
        matchLabels:
          app: rook-ceph-rgw
          rgw: s3
    ports:
    - protocol: TCP
      port: 57480
```
After kube-router upgraded to v1.2.3, pod selectors is not working. I have to change it to an `ipBlock` including all possible nodes.

**System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 1.3.0
 - Kube-Router Parameters: `- --run-router=true --run-firewall=true --run-service-proxy=false --bgp-graceful-restart=true --service-cluster-ip-range=10.233.0.0/17`
 - Kubernetes Version (`kubectl version`) : 1.21.3
 - Cloud Type: on premise
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 6 Nodes
