### ISSUE TITLE
Iptables rule for Direct Server Return Service still exist although service is removed.

### ISSUE THREAD

**Issue by napat1412** [cloudnativelabs/kube-router#1167]
**What happened**:
After kubernetes service that enable Direct Server Return is removed, I wait for sync iptables but iptables rule for Direct Server Return still exist.
I must flush iptables mangle before I re-assign ExternalIP address to new service
`iptables -t mangle -F`

----
**What you expected to happen**:
kube-router sync and remove iptables rules of removed DSR service.

---
**How can we reproduce the behavior you experienced?**:
Step 1: Deploy kube-router

Step 2: Create DSR servic
`kubectl delete -f iperf-svc.yaml`
File: iperf-svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-router.io/service.dsr: tunnel
  name: iperf
  namespace: default
  labels:
    app: iperf
spec:
  selector:
    app: iperf
  externalIPs: [192.168.0.25]
  ports:
  - name: iperf
    port: 5201
    targetPort: 5201
    protocol: TCP
  - name: iperf-udp
    port: 5201
    targetPort: 5201
    protocol: UDP
```

Step 3: Delete DSR servic
`kubectl delete -f iperf-svc.yaml`

Step 4: Wait and check iptables rule
`iptables-save`
```
...
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:KUBE-KUBELET-CANARY - [0:0]
-A PREROUTING -d 192.168.0.25/32 -p udp -m udp --dport 5201 -j MARK --set-xmark 0x369e/0xffffffff
-A PREROUTING -d 192.168.0.25/32 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1480
-A PREROUTING -d 192.168.0.25/32 -p tcp -m tcp --dport 5201 -j MARK --set-xmark 0x1062/0xffffffff
-A OUTPUT -d 192.168.0.25/32 -p udp -m udp --dport 5201 -j MARK --set-xmark 0x369e/0xffffffff
-A OUTPUT -d 192.168.0.25/32 -p tcp -m tcp --dport 5201 -j MARK --set-xmark 0x1062/0xffffffff
-A POSTROUTING -s 192.168.0.25/32 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1480
...
```

I run "kube-router --cleanup-config" but it can't remove iptables rule.
---

**Screenshots / Architecture Diagrams / Network Topologies **
If applicable, add those here to help explain your problem.

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 1.2.3 & 1.3.1
 - Kube-Router Parameters: 

Deploy kube-router with parameters.
```
        args:
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --bgp-graceful-restart=true
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - --v=7
        - --enable-overlay=false
        - --advertise-external-ip=true
        - --iptables-sync-period=2m
        - --ipvs-sync-period=2m
```
 - Kubernetes Version (`kubectl version`) : 1.21.2]
 - Cloud Type: on premise
 - OS: Almalinux 8.4
 - iptables v1.8.4 (nf_tables)
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 2

** Logs, other output, metrics **
There is no error log from kube-router.
