### ISSUE TITLE
kubeadm: run kube-router as service proxy

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#118]
Kubeadm runs kube-proxy as daemon set. Kube-proxy will use --kubeconfig file passed through configmap and looks like below

```
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://192.168.1.199:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

There is no way to generate kubeconfig for kube-router without modifying kubeadm. so it rules out the possibility.

In-cluser config is insufficient as we will have token, but kube-router does not know the master IP address. It will know cluster IP but, it runs in catch-22 situation. It does not know the endpoint to setup IPVS, so it can not access the API server. So its like need to access API server to access API server.

We need a way to run kube-router as replacement for kube-proxy.
