### ISSUE TITLE
pods cannot access its own cluster-ip If there is only one pods behind the cluster-ip

### ISSUE THREAD

**Issue by yuchunyun** [cloudnativelabs/kube-router#1235]
**What happened?**
create deployment and service, cluster-IP cannot be accessed within the container  If there is only one pods behind the cluster-ip.
If there are N pods on the back end, there is a probability of 1/N that it can not access
**What did you expect to happen?**
access to own cluster-ip inside the container
**How can we reproduce the behavior you experienced?**

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zdnscloud-limitedresources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zdnscloud-limitedresources
  template:
    metadata:
      labels:
        app: zdnscloud-limitedresources
    spec:
      containers:
      - name: zdnscloud-limitedresources
        image: docker.zdns.cn/safeguard/zcloud-limitedresources:v3.0.0
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: zdnscloud-limitedresources
spec:
  ports:
  - name: zdnscloud-limitedresources
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: zdnscloud-limitedresources
```
kubectl get pods -o wide
```
zdnscloud-limitedresources-58f7f9cbc9-sql9z   1/1     Running     0   102m    10.244.5.69   k06    <none>           <none>
```
kubectl get svc
```
zdnscloud-limitedresources     ClusterIP      10.96.0.8     <none>         6000/TCP                                       103m
```
ipvsadm -l -n
```
TCP  10.96.0.8:6000 rr
  -> 10.244.5.69:6000             Masq    1      0          0
```
kubectl exec -it zdnscloud-limitedresources-58f7f9cbc9-sql9z /bin/sh
```
/ # ip a | grep gl
    inet 10.244.5.69/24 brd 10.244.5.255 scope global eth0
/ # telnet 10.244.5.69 6000
Connected to 10.244.5.69

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

/ # telnet 10.96.0.8 6000
^C
/ # 
```

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`):  v1.4.0
 - Kube-Router Parameters: 
 ```
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --bgp-graceful-restart=true
        - --advertise-external-ip=true
        - --service-external-ip-range=10.1.201.0/24
        - --cluster-asn=64616
        - --peer-router-ips=10.1.254.1
        - --peer-router-multihop-ttl=5
        - --peer-router-asns=64615
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - --metrics-path=/metrics
        - --metrics-port=8080
        - --v=5
```
 - Kubernetes Version (`kubectl version`) :  v1.22.2
 - Cloud Type: Private clouds
 - Kubernetes Deployment Type: Kubeadm (--skip-phases=addon/kube-proxy)
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 8
