### ISSUE TITLE
networkpolicy are not enforced fast enough

### ISSUE THREAD

**Issue by HangjianQian** [cloudnativelabs/kube-router#1309]
**What happened?**
I've set up a networkpolicy which only permit ingress traffic in the same namespace 'a'.When new pod start running, it can't  access the other pods in the same namespace at first few seconds.This may due to networkpolicy enforced too slow.

**What did you expect to happen?**
new pods could access the old pods in the same namespace.

**How can we reproduce the behavior you experienced?**
1.  Step 1
    create a namespace 'a'
```
kubectl create namespace a
```
2. Step 2
    create network policy for namespace 'a'
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: a
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: a
      ports:
        - protocol: TCP
          port: 80
```
3. Step 3
    create some nginx for access test
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: a
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
4. Step 4
   run new pod in namespace 'a' to test access,  10.233.0.24 is the ip of the nginx pod which created in Step 3.
```
kubectl -n a run -i -t busybox --image=busybox --restart=Never -- sh -c  "nc -zv 10.233.0.24 80"
```
  then it offen shows when src pod and dst pod are in different nodes.
```
pod a/busybox terminated (Error)
```
 But if wait a few seconds before `nc` run, the result is ok:
```
kubectl -n a run -i -t busybox --image=busybox --restart=Never -- sh -c  "sleep 2;nc -zv 10.233.0.24 80"
```

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 1.4.0
 - Kube-Router Parameters: --run-router=true --run-firewall=true --run-service-proxy=true --bgp-graceful-restart=true --kubeconfig=/var/lib/kube-router/kubeconfig
 - Kubernetes Version (`kubectl version`) : 1.23.6
 - Cloud Type:  metal
 - Kubernetes Deployment Type:  Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 200 nodes.
