### ISSUE TITLE
support fot hostPort

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#168]
Not sure if there is any changes needed in kube-router. Will investigate further.

https://github.com/kubernetes/kubernetes/issues/23920

CNI plug-in

https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap

If its just manifest changes, then need to update KOPS manifest.

**Comment by jpiper** [comment]
Kubernetes 1.9 ships with CNI 0.6.0 which has the portmap plugin, so I think you'd just need to enable it in the CNI conf with something like this (note: haven't tested this!)

```yaml
cni-conf.json: |
  {
     "cniVersion":"0.3.0",
     "name":"mynet",
     "plugins":[
        {
           "name":"kubernetes",
           "type":"bridge",
           "bridge":"kube-bridge",
           "isDefaultGateway":true,
           "ipam":{
              "type":"host-local"
           }
        },
        {
           "type":"portmap",
           "capabilities":{
              "snat": true
              "portMappings":true
           }
        }
     ]
  }
```

**Comment by murali-reddy** [comment]
@jpiper thanks! will test out if that simple, then no reason not to support it :)

**Comment by t3hmrman** [comment]
Hey just want to confirm that @jpiper is spot on right minus one `,` (near `snat` capability). 

I just set up `fluentd` on my k8s cluster and went from immediate `connection refused` to working communication by putting the following configuration in `/etc/cni/net.d/10-kuberouter.conflist`:

```json
{
  "cniVersion": "0.3.0",
  "name": "net",
  "plugins": [
    {
      "isDefaultGateway": true,
      "name": "kubernetes",
      "type": "bridge",
      "bridge": "kube-bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.244.1.0/24"
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "snat":true,
        "portMappings":true
      }
   }
  ]
}
```

After that, a restart of `containerd` and `cri-containerd` via `systemctl` were all it took to get communication working, was able to test my connection to `hostPort`ed `fluentd` Pod from an `alpine` pod in a different namespace by using the Host IP & Python (for the `fluent-logger` library).

**Comment by felipejfc** [comment]
kube-router referrences /etc/cni/net.d/10-kuberouter.conf in some points of the code, we should first change them to accept an envvar pointing to the conf file, since to use an array on plugins we have to use conflist extension.

https://github.com/cloudnativelabs/kube-router/search?utf8=%E2%9C%93&q=%2Fetc%2Fcni%2Fnet.d%2F10-kuberouter.conf&type=

**Comment by t3hmrman** [comment]
Hey @murali-reddy is this anything more than a documentation change to fix? It seems like it shouldn't be within kube-router's purview to setup CNI configurations, outside of giving an example of a working default?

**Comment by murali-reddy** [comment]
@t3hmrman i believe some code cleanup is required to start with.

https://github.com/cloudnativelabs/kube-router/blob/4e768b146741da91a3253445b7b1833fee1f5b8d/app/controllers/network_routes_controller.go#L89-L93

Like @felipejfc mentioned right now conf file path is hard coded to `/etc/cni/net.d/10-kuberouter.conf` that should be removed from the code to env var.

Also, I think parsing code needs to change to support array of plugins.

**Comment by murali-reddy** [comment]
I am working on the fix. I will update with my findings.

**Comment by t3hmrman** [comment]
Thanks for the thorough work -- want to be clear I wasn't trying to rush you just wanted to see if it was something someone could easily contribute!

Cheers

**Comment by murali-reddy** [comment]
I have raised https://github.com/cloudnativelabs/kube-router/pull/335

If any one want to review it and give it try please use the image `cloudnativelabs/kube-router-git:hostport`

**Comment by NiraliSupe** [comment]
@murali-reddy Hello
A newby question. I am using the kube-router manifest file from https://github.com/murali-reddy/kube-router/blob/hostport/daemonset/kubeadm-kuberouter-all-features-hostport.yaml
I am getting the following error:
``` 
 3647 cni.go:259] Error adding network: no IP ranges specified
 3647 cni.go:227] Error while adding to cni network: no IP ranges specified
```
Could you please help with this?

**Comment by murali-reddy** [comment]
Actually i am running into same issue with kubelet when i enable `.conflist` @NiraliSupe 

@t3hmrman is there any specific flag that needs to be enabled for kubelet. I tried with Kubernetes `1.9.3` my `.conflist` is same as one you mentioned except additional `subnet` field added to `ipam`

**Comment by murali-reddy** [comment]
> A newby question. I am using the kube-router manifest file from https://github.com/murali-reddy/kube-router/blob/hostport/daemonset/kubeadm-kuberouter-all-features-hostport.yaml
I am getting the following error:

> 3647 cni.go:259] Error adding network: no IP ranges specified
> 3647 cni.go:227] Error while adding to cni network: no IP ranges specified

@NiraliSupe how does your `/etc/cni/net.d/10-kuberouter.conflist` file content looks like?

**Comment by t3hmrman** [comment]
@murali-reddy I'm relatively sure all I needed to do was restart the `cri-containerd` and `containerd` services (which I use for my container run time).

I do have my cluster and service CIDRs set, I'd assume that's not what's missing for you guys? 

Here's my resource configuration for the `kube-router` `ConfigMap`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-router-cfg
  namespace: kube-system
  labels:
    tier: node
    k8s-app: kube-router
data:
  cni-conf.json: |
    {
      "name":"kubernetes",
      "type":"bridge",
      "bridge":"kube-bridge",
      "isDefaultGateway":true,
      "ipam": {
        "type":"host-local"
      }                                                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                                                             
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusterCIDR: "10.244.0.0/16"
    clusters:
    - name: cluster
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: "http://127.0.0.1:8080"
    users:
    - name: kube-router
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: cluster
        user: kube-router
      name: kube-router-context
    current-context: kube-router-context
```
I think you can safely ignore the `cni-conf.json` part -- all I can see that might help is the `kubeconfig` I give it (has a CIDR in it), but I doubt that is the problem.

The full `DaemonSet`:

```yaml
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-router
        tier: node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: kube-router
      containers:
      - name: kube-router
        image: cloudnativelabs/kube-router
        imagePullPolicy: Always
        args:
        - "--run-router=true"
        - "--run-firewall=true"
        - "--run-service-proxy=true"
        - "--kubeconfig=/var/lib/kube-router/kubeconfig"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /healthz
            port: 20244
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d
        - name: kubeconfig
          mountPath: /var/lib/kube-router
          readOnly: true
      initContainers:
      - name: install-cni
        image: busybox
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - set -e -x;
          if [ ! -f /etc/cni/net.d/10-kuberouter.conf ]; then
            TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
            cp /etc/kube-router/cni-conf.json ${TMP};
            mv ${TMP} /etc/cni/net.d/10-kuberouter.conf;
          fi;
          if [ ! -f /var/lib/kube-router/kubeconfig ]; then
            TMP=/var/lib/kube-router/.tmp-kubeconfig;
            cp /etc/kube-router/kubeconfig ${TMP};
            mv ${TMP} /var/lib/kube-router/kubeconfig;
          fi
        volumeMounts:
        - mountPath: /etc/cni/net.d
          name: cni-conf-dir
        - mountPath: /etc/kube-router
          name: kube-router-cfg
        - name: kubeconfig
          mountPath: /var/lib/kube-router
      hostNetwork: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: cni-conf-dir
        hostPath:
          path: /etc/cni/net.d
      - name: kube-router-cfg
        configMap:
          name: kube-router-cfg
      - name: kubeconfig
        hostPath:
          path: /var/lib/kube-router
```

Alot of things will be specific to my setup, but the only thing I think might be difference is probably the inclusion of the `kubeconfig` flag and the `ConfigMap`
