### ISSUE TITLE
Network policy makes master unreachable

### ISSUE THREAD

**Issue by hjdr4** [cloudnativelabs/kube-router#180]
Hello,

I'm trying to restrict Kubernetes dashboard access using a network policy (dashboard does not support client certificates, so I want to use proxy access from API server that validates client certs and block from in-cluster access).

When I apply my policy, I loose access to my cluster. Kubectl cannot contact the master anymore.

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-dashboard
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
```
From what I understand of the doc, this should allow everything in kube-system namespace to reach kubernetes-dashboard, block everything else to the dashboard only, and leave all my other pods as they are, free to communicate.

When I apply this policy, it breaks my master. I cannot join my API server anymore.

```
kubectl -s http://192.168.1.34:8080 get pods -o json --selector=k8s-app=kubernetes-dashboard --namespace=kube-system | jq '.items[] | .status | .podIP'
"172.17.0.3"
```

It applies a bunch of iptables rules : 
[iptables.txt](https://github.com/cloudnativelabs/kube-router/files/1360886/iptables.txt)

I'm using the latest kube-router Docker image and Kubernetes 1.8.
