### ISSUE TITLE
systemd-networkd restart silently breaks kube-router

### ISSUE THREAD

**Issue by ninja-** [cloudnativelabs/kube-router#1815]
## What happened?
Basically without ManageForeignRoutingPolicyRules=no, restarting systemd-networkd will silently break kube-router without any error messages - until the kube-router pod is deleted and restarted.

## What did you expect to happen?
I would expect kube-router to detect the problem and self-heal - exiting would be fine, as kube-router pod restart is confirmed to fix this.

It would be nice to detect lack of ManageForeignRoutingPolicyRules=no and print a big big warning on start as well.

## How can we reproduce the behavior you experienced?

1. Create a k0s cluster with kube-router
2. systemctl restart systemd-networkd on one of the nodes
3. everything seems to work just fine, most traffic flows, but access to internal "Kubernetes API" service will  start failing, like running kubectl from within container

## Screenshots / Architecture Diagrams / Network Topologies

If applicable, add those here to help explain your problem.

## System Information (please complete the following information)

- Kube-Router Version (`kube-router --version`): [e.g. 1.0.1]
- Kube-Router Parameters: [e.g. --run-router --run-service-proxy --enable-overlay --overlay-type=full etc.]
- Kubernetes Version (`kubectl version`) : [e.g. 1.18.3]
- Cloud Type: [e.g. AWS, GCP, Azure, on premise]
- Kubernetes Deployment Type: [e.g. EKS, GKE, Kops, Kubeadm, etc.]
- Kube-Router Deployment Type: [e.g. DaemonSet, System Service]
- Cluster Size: [e.g. 200 Nodes]

## Logs, other output, metrics

Please provide logs, other kind of output or observed metrics here.

## Additional context
https://github.com/k0sproject/k0s/issues/5623 - a little more context and logs

**Comment by aauren** [comment]
It would be helpful to know what version of kube-router is being used here? Ever since kube-router v2.0.0 kube-router has a route syncing controller that keeps track of its routes and restores them as needed. My guess is that kube-router will eventually restore itself automatically the next time that the route sync controller ticks again.

By default this happens every 5 minutes, however the user can override this value via the parameter `--routes-sync-period`

However, even with that, there is essentially not a whole lot that kube-router can do to prevent systems from coming in and messing with its state on routes or really anything else.

Linux doesn't expose any way to "watch" routes, so the only way that kube-router could seamlessly restore routes from a system that decides that it wants to purge anything that it doesn't know about like networkd, would be to non-stop poll the state of the routing table which would be incredibly ineffecient.

At the end of the day, kube-router doesn't have anything to do with the networkd project, so I would say that it would be better to file this issue upstream with networkd and try to push for more sane defaults. Defaulting this setting to "yes" seems a tad ridiculous and myopic. For the record, kube-router and most other projects go out of their way to preserve the routing, iptables, ipset, etc states that are not ours so that we don't negatively impact things running on the same system.

All this being said, I bet that you will not be the only person that runs into this. systemd is essentially the default init system for Linux, and several projects have defaulted to using networkd. If you would like to submit a PR for some documentation improvements that mention this caveat, I'm sure that it would help other users. I would suggest adding something into: https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md

**Comment by ninja-** [comment]
it's     image: quay.io/k0sproject/kube-router:v2.4.1-iptables1.8.9-0

the 5 minut period does nothing I am afraid, the cluster was broken for hours - annoyingly, either Ubuntu or Hetzner configured these unattended upgrades by default now which resulted in systemd-networkd restart at a random time

**Comment by aauren** [comment]
Can you send me the full deployment config for kube-router? I would like to see what arguments it was started with.

**Comment by ninja-** [comment]
```
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-router
      tier: node
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: kube-router
        tier: node
    spec:
      containers:
      - args:
        - --run-router=true
        - --run-service-proxy=false
        - --bgp-graceful-restart=true
        - --enable-ipv4=true
        - --enable-ipv6=false
        - --auto-mtu=true
        - --run-firewall=true
        - --metrics-port=8080
        - --hairpin-mode=true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KUBE_ROUTER_CNI_CONF_FILE
          value: /etc/cni/net.d/10-kuberouter.conflist
        image: quay.io/k0sproject/kube-router:v2.4.1-iptables1.8.9-0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: kube-router
        ports:
        - containerPort: 20244
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          periodSeconds: 3
          successThreshold: 3
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 250m
            memory: 16Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /etc/cni/net.d
          name: cni-conf-dir
        - mountPath: /run/xtables.lock
          name: xtables-lock
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      initContainers:
      - args:
        - install
        image: quay.io/k0sproject/cni-node:1.3.0-k0s.0
        imagePullPolicy: IfNotPresent
        name: install-cni-bins
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin
      - command:
        - /bin/sh
        - -c
        - set -e -x; if [ ! -f /etc/cni/net.d/10-kuberouter.conflist ]; then if [
          -f /etc/cni/net.d/*.conf ]; then rm -f /etc/cni/net.d/*.conf; fi; TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
          cp /etc/kube-router/cni-conf.json ${TMP}; mv ${TMP} /etc/cni/net.d/10-kuberouter.conflist;
          fi
        image: quay.io/k0sproject/kube-router:v2.4.1-iptables1.8.9-0
        imagePullPolicy: IfNotPresent
        name: install-cniconf
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cni/net.d
          name: cni-conf-dir
        - mountPath: /etc/kube-router
          name: kube-router-cfg
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-router
      serviceAccountName: kube-router
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni-conf-dir
      - hostPath:
          path: /opt/cni/bin
          type: DirectoryOrCreate
        name: cni-bin
      - configMap:
          defaultMode: 420
          name: kube-router-cfg
        name: kube-router-cfg
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 2
  updatedNumberScheduled: 3
```
