### ISSUE TITLE
BGP Route Reflector Feature

### ISSUE THREAD

**Issue by ut0mt8** [cloudnativelabs/kube-router#192]
First a big thanks for this very promising project. This is what I expect to be the future of the kubernetes networking :)

kube-router could be enabled to peer with external router. This is fine. 
But in my understanding the external router could peer with all node/kuberouter instances. For a small cluster this is ok; but for a bigger one (say 100 nodes) it s not really doable.

First problem : it doesn't scale, a full mesh of 100 nodes plus one external routeur is a big waste, and will certainly cause some convergence issue.
Second problem : for the external router point adding a node will require a reconfiguration of the bgp configuration (on a linux box with quagga/bird, this can be scripted, but on a real network equipment no).

So it will be really cool if an instance of kube-router could be specialised as a Route Reflector both for bgp scaling in the kubernetes network, and for allowng simple peering with externals routers.

Does it make sense ?

**Comment by murali-reddy** [comment]
@ut0mt8 thanks for your comments. Adding route reflector certianly make sense. Kube-router has to support route reflector at some time as the adoption of kube-router increase and there is need from user for large cluster deployment.

**Comment by ut0mt8** [comment]
I wait for this :) Currently I think I can use two RRs with two external bgp peers, disabling meshing.
The only problem is that adding a new node need a manual configuration of the RRs. (I surely can automate this watching api server)

**Comment by murali-reddy** [comment]
Sorry this request did not make any progress. There are two critical issues ( #202 slow convergence and #220 routes getting deleted during rolling upgrades) that are affecting users. Once they are addressed I am hoping that kube-router's routing has a solid ground on which more advanced features like route reflector can be added.

**Comment by ut0mt8** [comment]
#202 could be handled with RRs :) doing a full mesh of >50 bgp speaker is a bad idea in every context (I was network engineer in previous job).

**Comment by SEJeff** [comment]
@ut0mt8 you can now do a single AS per rack model with the current kube-router, which is an alternative to using reflectors depending on your topology.

We specify which using node annotations such as:

```
net.kuberouter.node.bgppeer.address=10.2.3.4
net.kuberouter.node.bgppeer.asn=654321
net.kuberouter.nodeasn=654322
```

Your kube-router daemonset can have args such as:

```yaml
    spec:
      containers:
      - args:
        - --run-router=true
        - --run-firewall=false
        - --run-service-proxy=true
        - --cluster-cidr=10.2.3.0/18
        - --nodes-full-mesh=false
        - --enable-overlay=false
        - --kubeconfig=/etc/kubernetes/kubeconfig
```
