### ISSUE TITLE
kube-router is using too much CPU and memory

### ISSUE THREAD

**Issue by alkar** [cloudnativelabs/kube-router#228]
Spec:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-router-cfg
  namespace: kube-system
  labels:
    tier: node
    k8s-app: kube-router
data:
  cni-conf.json: |
    {
      "name":"kubernetes",
      "type":"bridge",
      "bridge":"kube-bridge",
      "isDefaultGateway":true,
      "ipam": {
        "type":"host-local"
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-router
  namespace: kube-system
  labels:
    k8s-app: kube-router
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        k8s-app: kube-router
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: kube-router
        image: cloudnativelabs/kube-router:v0.0.19
        args:
          - --run-router=true
          - --run-firewall=true
          - --run-service-proxy=true
          - --kubeconfig=/var/lib/kube-router/kubeconfig/kubeconfig
        securityContext:
          privileged: true
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: lib-modules
            mountPath: /lib/modules
            readOnly: true
          - name: cni-conf-dir
            mountPath: /etc/cni/net.d
          - name: kubeconfig
            mountPath: /var/lib/kube-router/kubeconfig
            readOnly: true
      initContainers:
      - name: install-cni
        image: busybox
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - set -e -x;
            if [ ! -f /etc/cni/net.d/10-kuberouter.conf ]; then
              TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
              cp /etc/kube-router/cni-conf.json ${TMP};
              mv ${TMP} /etc/cni/net.d/10-kuberouter.conf;
            fi;
            wget -qO- https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz | tar -xz -C /opt/cni/bin ./host-local ./bridge ./loopback
        env:
          - name: CNI_VERSION
            value: v0.6.0
        volumeMounts:
          - name: cni-conf-dir
            mountPath: /etc/cni/net.d
          - name: cni-bin-dir
            mountPath: /opt/cni/bin
          - name: kube-router-cfg
            mountPath: /etc/kube-router
      hostNetwork: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: cni-conf-dir
          hostPath:
            path: /etc/cni/net.d
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: kube-router-cfg
          configMap:
            name: kube-router-cfg
        - name: kubeconfig
          configMap:
            name: kube-router-kubeconfig
```

- CPU usage on master nodes after the transition to `kube-router` (it looks similar on worker nodes)
![kube-router-master-cpu](https://user-images.githubusercontent.com/898156/33276638-0363c556-d38e-11e7-87eb-52ee557a2f9a.png)

- CPU usage of kube-router pods
![kube-router-cpu](https://user-images.githubusercontent.com/898156/33276661-1818c08c-d38e-11e7-9fbf-32f14c11f070.png)

- Memory usage of kube-router pods
![kube-router-mem](https://user-images.githubusercontent.com/898156/33276692-29382a24-d38e-11e7-8663-a3d7c78262de.png)
