### ISSUE TITLE
Odd IPVS connection issues

### ISSUE THREAD

**Issue by dl00** [cloudnativelabs/kube-router#237]
I am amazed I have not caught this issue much sooner, but here goes:

I set up the following service:

```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: kube-system
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
spec:
  type: NodePort
  selector:
    k8s-app: nginx-ingress-controller
  ports:
  - name: http
    port: 80
    nodePort: 30080
    targetPort: http
```

The IPVS records are created as expected:
```
[beald@gerudo ~]$ sudo ipvsadm -ln | grep -A1 30080
TCP  192.168.1.220:30080 rr
  -> 10.244.3.80:80               Masq    1      0          0         
--
TCP  127.0.0.1:30080 rr
  -> 10.244.3.80:80               Masq    1      0          0         
--
TCP  192.168.240.1:30080 rr
  -> 10.244.3.80:80               Masq    1      0          0
```

Running `curl 10.244.3.80` works as expected, returning a web page. However, running `curl 127.0.0.1:30080` just hangs and finally times out. Some more curl details:

* `curl 192.168.1.220:30080` works, but _only_ from the system that actually has that IP address
* `curl 192.168.1.219:30080` (the machine that the pod being referred at `10.244.3.80` is on) works.

Seems like there might be some wierd network interface resolution thing going on, but I am not sure. This probobly has to do with the issue that @mqliang reported earlier on my merge (#217).
