### ISSUE TITLE
Shouldn't Networkpolicy apply to peers AND ports, rather than OR?

### ISSUE THREAD

**Issue by johanot** [cloudnativelabs/kube-router#389]
I have the following netpol:

```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: test   
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: toolbox 
  - ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      run: test   
  policyTypes:
  - Ingress
```

My observation is that I can access my run=test pod, **either**:

- on port 80 from _anywhere_
**or**
- on _any_ port from my run=toolbox pods

**at the same time**

I don't think this is a correct interpretation of the netpol resource. In my opinion, it only make sense to apply the rule on the combination of peers and ports. Meaning that I expect the following behavior from my above example:

- Allow **only** ingress traffic from podSelector matchLabels run=toolbox, on **only** port 80.

If I really wanted the current behavior, I would create two separate policies. One allowing all ingress traffic (without specifying peers) to port 80, another allowing all ingress traffic from a specific pod-selector (without specifying ports).

**Comment by murali-reddy** [comment]
@johanot This case is handled as far i can see. Could you please share how your iptables filter table look like?

```go
	// run through all the ingress rules in the spec and create iptable rules
	// in the chain for the network policy
	for i, ingressRule := range policy.ingressRules {

		if len(ingressRule.srcPods) != 0 {
```

```go
			if len(ingressRule.ports) != 0 {
				// case where 'ports' details and 'from' details specified in the ingress rule
				// so match on specified source and destination ip's and specified port and protocol
				for _, portProtocol := range ingressRule.ports {
					comment := "rule to ACCEPT traffic from source pods to dest pods selected by policy name " +
						policy.name + " namespace " + policy.namespace
					args := []string{"-m", "comment", "--comment", comment,
						"-m", "set", "--set", srcPodIpSetName, "src",
						"-m", "set", "--set", targetDestPodIpSetName, "dst",
						"-p", portProtocol.protocol,
						"--dport", portProtocol.port,
						"-j", "ACCEPT"}
```

**Comment by johanot** [comment]
`$ sudo iptables -F `

(wait for reconcile)

`$ sudo iptables -S KUBE-NWPLCY-CR6XZRVC2F6OGNFE`

`
-A KUBE-NWPLCY-CR6XZRVC2F6OGNFE -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name test namespace default" -m set --match-set KUBE-SRC-TADRR5V3RMRQF6YX src -m set --match-set KUBE-DST-CR6XZRVC2F6OGNFE dst -j ACCEPT
`
**^^ Correct**

`
-A KUBE-NWPLCY-CR6XZRVC2F6OGNFE -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name: test namespace default" -m set --match-set KUBE-DST-CR6XZRVC2F6OGNFE dst -m tcp --dport 80 -j ACCEPT
`
**^^ Wrong**

@murali-reddy 
Could look like `ingressRule.matchAllSource` is true for some reason? But this is just a guess. I would have to insert some more verbose logging to see which if-else-blocks get triggered.

**Comment by johanot** [comment]
Well no.. First rule lacks dport, second rule lacks src-match-set. :/ strange

**Comment by johanot** [comment]
@murali-reddy Oh... Sometimes I just hate yaml :(

Compare the below spec with my original post.

```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: test   
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: toolbox 
    ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      run: test   
  policyTypes:
  - Ingress
```

Looks like I accidentally made _two_ ingress sections, one with a ports definition and another with from definition. After changing the spec I get the one single iptables rule I expect:

`-A KUBE-NWPLCY-CR6XZRVC2F6OGNFE -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name toolbox namespace default" -m set --match-set KUBE-SRC-TADRR5V3RMRQF6YX src -m set --match-set KUBE-DST-CR6XZRVC2F6OGNFE dst -m tcp --dport 80 -j ACCEPT`
