### ISSUE TITLE
regression: namespaceSelector-NetworkPolicy does not work in v0.2.0-beta4

### ISSUE THREAD

**Issue by xanonid** [cloudnativelabs/kube-router#412]
With kube-router v0.2.0-beta4, a NetworkPolicy with namespaceSelector, like

```
 ...
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: otherNamespace
     - podSelector:
        matchLabels:
          podLabel: "value"
  ...         
```
does work only partially. The IPs of pods in otherNamespace are not added to the corresponding ipset, only the pods matching the podLabel. With v0.1.0, the same NetworkPolicy works correctly.

Used versions:
Kubernetes v1.9.7
kube-router v0.2.0-beta4
