### ISSUE TITLE
kube-router won't start: Failed to create network routing controller: Failed to create ipset set on system: ipset v6.34: Kernel error received: set type not supported

### ISSUE THREAD

**Issue by jforman** [cloudnativelabs/kube-router#539]
I am trying to the "run-router" functionality of kube-router to propoagate routing tables to my various k8s nodes, but receiving the following error in the logs:
```
I0921 00:19:45.773157       1 kube-router.go:207] Running /usr/local/bin/kube-router version v0.2.0, built on 2018-09-12T08:03:59-0400, go1.10.3
Failed to run kube-router: Failed to create network routing controller: Failed to create ipset set on system: ipset v6.34: Kernel error received: set type not supported
```

I'm not sure what might be wrong with my version of Ubuntu, or perhaps the container image provided by kube-router, to cause this error. Any help greatly apprecaited.

My nodes themselves are Ubuntu Minimal Builds:
```
root@deva-controller0:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

I am using a daemonset configuration for kube-router:
```
---
# https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/generic-kuberouter-only-advertise-routes.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-router
        tier: node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: kube-router
      containers:
      - name: kube-router
        image: cloudnativelabs/kube-router
        imagePullPolicy: Always
        args:
        - "--run-router=true"
        - "--run-firewall=false"
        - "--run-service-proxy=false"
        - "--kubeconfig=/opt/kubernetes/kube-router.kubeconfig"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /healthz
            port: 20244
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        securityContext:
          privileged: true
        volumeMounts:
          - name: kubeconfig-volume
            mountPath: /opt/kubernetes/
          - name: cni-kuberouter-conf
            mountPath: /etc/cni/net.d/10-kuberouter.conf
      volumes:
        - name: kubeconfig-volume
          secret:
            secretName: kube-router-kubeconfig
        - name: cni-kuberouter-conf
          hostPath:
            path: /etc/cni/net.d/10-bridge.conf
            type: File
      hostNetwork: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-router
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-router
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - nodes
      - endpoints
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - extensions
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-router
subjects:
- kind: ServiceAccount
  name: kube-router
  namespace: kube-system

```

```
root@deva-controller0:~# cat /etc/cni/net.d/10-bridge.conf 
{
    "cniVersion": "0.3.1",
    "name": "bridge",
    "type": "bridge",
    "bridge": "cnio0",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "ranges": [
          [{"subnet": "10.244.7.0/24"}]
        ],
        "routes": [{"dst": "0.0.0.0/0"}]
    }

```
