### ISSUE TITLE
Kube-Router does not support rolling-update and 0 downtime

### ISSUE THREAD

**Issue by BobbyJohansen** [cloudnativelabs/kube-router#589]
Issue: When running a service with a deployment configuration with a rolling deployment policy the pods still go offline for an amount of time causing brief downtime in our service.

Expectation: kuberouter uses a load balancing policy (we use Round Robin) and changes available hosts in a sequence that causes no downtime I.E:
1) new pod comes up and liveliness probe deems the pod healthy, kube-router adds the pod to the round robin list of available pods.
2) old pod is drained of all requests and removed from the round robin list of available pods then terminated by the scheduler (or who ever is responsible) 
3) repeat for the rest of your nodes...

Current Experience: 
1) new pod spins up waiting for liveliness probe - http requests receive 502s, assumably because its not ready
2) old pod goes down and more 502s pursue
3) eventually round robin list is updated and 200s come back (whole process takes maybe 10 - 15 seconds

Configs:
Rolling update for deployment:
```type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```

liveliness probe:
```livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 1
          failureThreshold: 5
          timeoutSeconds: 30
```

Kube-router version: v0.0.20
kubernetes version: 1.8.5

I am wondering if I am trivializing this problem however it is a requirement for us and wondering if there are plans to resolve this in kube-router since it is currently the easiest to setup vs alternatives.

**Comment by roffe** [comment]
are you using `--bgp-graceful-restart` in your KR deployment?

**Comment by roffe** [comment]
There is no graceful termination in kube-router at the moment. When you are doing rolling upgrades the pod is instantly removed from the IPVS service and has no chance to do a graceful shutdown network wise. It does not matter that you have a delayed shutdown phase or health checks in the pod.

**Comment by mk01** [comment]
@BobbyJohansen 

update your deployment's specs by adding 
```
minReadySeconds:
```

and beside livenessProbe add also
```
readinessProbe
```
generally, minReadySeconds should be value higher than livenessProbe failure, so that in case new generation is buggy and won't start, the previous gen won't be ever terminated.

with setup like that, new destination won't be added before it's readinessProbe is OK. as soon as it passes probe, minReadySeconds kicks in and both are serving the requests. after the readySeconds period passes, the old pod is terminated. together with
```
net.ipv4.vs.expire_nodest_conn=0
```

this is h2load 120s test with deployment of kubernetes dashboard svc set with (rolling update was triggered by changing terminationGracePeriodSeconds)

```
spec:
  minReadySeconds: 60
...
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
```

```
yy@XXXXXX:~$ h2load  -r 1 -c 120 -n 120  https://[fde4:1234::a521]
starting benchmark...
spawning thread #0: 120 total client(s). Up to 1 client(s) will be created every 1s 120 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-ECDSA-AES128-GCM-SHA256
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% of clients started
progress: 20% of clients started
progress: 30% of clients started
progress: 40% of clients started
progress: 50% of clients started
progress: 60% of clients started
progress: 70% of clients started
progress: 80% of clients started
progress: 90% of clients started
progress: 100% of clients started

finished in 119.16s, 1.01 req/s, 1.11KB/s
requests: 120 total, 120 started, 120 done, 120 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 120 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 132.66KB (135840) total, 10.31KB (10560) headers (space savings 50.28%), 116.02KB (118800) data
                     min         max         mean         sd        +/- sd
time for request:     4.46ms     96.59ms     39.89ms     17.48ms    75.00%
time for connect:    10.63ms    194.45ms    122.75ms     35.83ms    77.50%
time to 1st byte:    15.89ms    234.10ms    162.66ms     48.20ms    74.17%
req/s           :       4.27       62.72        8.02        8.28    93.33%
```
