### ISSUE TITLE
NetworkPolicy selector doesn't work as expected

### ISSUE THREAD

**Issue by bazuchan** [cloudnativelabs/kube-router#614]
Pods:
```
% kubectl get pods -o wide -n monitoring
NAME                                   READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE   READINESS GATES                                                                     
alertmanager-main-0                    2/2     Running   0          17h   100.99.3.6      kw1    <none>           <none>
alertmanager-main-1                    2/2     Running   0          17h   100.99.5.8      kw3    <none>           <none>
alertmanager-main-2                    2/2     Running   0          17h   100.99.4.7      kw2    <none>           <none>
grafana-6689854d5-bbr4w                1/1     Running   0          17h   100.99.4.5      kw2    <none>           <none>
kube-state-metrics-7cd987ffdf-kp6rj    4/4     Running   0          14h   100.99.4.8      kw2    <none>           <none>
node-exporter-cfgn2                    2/2     Running   0          17h   100.100.20.13   kc3    <none>           <none>
node-exporter-hl4dk                    2/2     Running   0          17h   100.100.20.11   kc1    <none>           <none>
node-exporter-kbxnk                    2/2     Running   0          17h   100.100.20.41   kw1    <none>           <none>
node-exporter-lwcv6                    2/2     Running   0          17h   100.100.20.43   kw3    <none>           <none>
node-exporter-n9jjh                    2/2     Running   0          17h   100.100.20.42   kw2    <none>           <none>
node-exporter-tz8h4                    2/2     Running   0          17h   100.100.20.12   kc2    <none>           <none>
prometheus-adapter-5cc8b5d556-k5cmc    1/1     Running   0          17h   100.99.5.6      kw3    <none>           <none>
prometheus-k8s-0                       3/3     Running   1          17h   100.99.4.6      kw2    <none>           <none>
prometheus-k8s-1                       3/3     Running   1          17h   100.99.3.7      kw1    <none>           <none>
prometheus-operator-5cfb7f4c54-7vqgb   1/1     Running   0          17h   100.99.5.5      kw3    <none>           <none>
```
Desired selector:
```
% kubectl get pods -o wide -n monitoring --selector 'app notin (node-exporter)'
NAME                                   READY   STATUS    RESTARTS   AGE   IP           NODE   NOMINATED NODE   READINESS GATES                                                                        
alertmanager-main-0                    2/2     Running   0          17h   100.99.3.6   kw1    <none>           <none>
alertmanager-main-1                    2/2     Running   0          17h   100.99.5.8   kw3    <none>           <none>
alertmanager-main-2                    2/2     Running   0          17h   100.99.4.7   kw2    <none>           <none>
grafana-6689854d5-bbr4w                1/1     Running   0          17h   100.99.4.5   kw2    <none>           <none>
kube-state-metrics-7cd987ffdf-kp6rj    4/4     Running   0          14h   100.99.4.8   kw2    <none>           <none>
prometheus-adapter-5cc8b5d556-k5cmc    1/1     Running   0          17h   100.99.5.6   kw3    <none>           <none>
prometheus-k8s-0                       3/3     Running   1          17h   100.99.4.6   kw2    <none>           <none>
prometheus-k8s-1                       3/3     Running   1          17h   100.99.3.7   kw1    <none>           <none>
prometheus-operator-5cfb7f4c54-7vqgb   1/1     Running   0          17h   100.99.5.5   kw3    <none>           <none>
```
NetworkPolicy:
```
apiVersion: v1  
kind: List                       
items:      
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:                       
    name: int        
    namespace: monitoring
  spec:             
    podSelector:         
      matchExpressions:
        - {key: app, operator: NotIn, values: [node-exporter]}
    policyTypes:
    - Ingress
    ingress:
    - from:     
      - podSelector:             
          matchExpressions:
            - {key: app, operator: NotIn, values: [node-exporter]}
```
```
% kubectl describe networkpolicy -n monitoring int
Name:         int
Namespace:    monitoring
Created on:   2018-12-18 12:33:08
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"int","namespace":"monitoring"},"spec":{"i...
Spec:
  PodSelector:     app notin (node-exporter)
  Allowing ingress traffic:
    To Port: <any> (traffic allowed to all ports)
    From:
      PodSelector: app notin (node-exporter)
  Allowing egress traffic:
    <none> (Selected pods are isolated for egress connectivity)
  Policy Types: Ingress
```

Resulting rules:
```
# iptables -S KUBE-NWPLCY-3QP6JVICGDL7DNXI
-N KUBE-NWPLCY-3QP6JVICGDL7DNXI                                                                                                                                                                       
-A KUBE-NWPLCY-3QP6JVICGDL7DNXI -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name int namespace monitoring" -m set --match-set KUBE-SRC-6SBOJFW5CCTQDW42 src -m set --match-set KUBE-DST-Z6CNPD5VQ53PLXNT dst -j ACCEPT
```
```
# ipset save KUBE-DST-Z6CNPD5VQ53PLXNT
create KUBE-DST-Z6CNPD5VQ53PLXNT hash:ip family inet hashsize 1024 maxelem 65536 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.5.6 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.4.6 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.100.20.11 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.3.7 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.4.7 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.100.20.13 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.5.5 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.100.20.43 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.5.8 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.3.6 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.100.20.12 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.100.20.41 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.4.5 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.99.4.8 timeout 0
add KUBE-DST-Z6CNPD5VQ53PLXNT 100.100.20.42 timeout 0
```

Ipset contains ips of node-exporter-* pods, but shouldn't.

**Comment by tommyknows** [comment]
same here - it seems like `matchLabels` works, but `matchExpressions` does not.
Tried the following:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-allow
  namespace: search
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: "nginx-ingress"
                operator: In
                values: ["true"]
      ports:
        - port: 3000
  podSelector: {}
  policyTypes:
    - Ingress
```

What I want is to allow traffic from all namspaces that have the `nginx-ingress` label. 
I also tried having the following `matchExpression`:
```yaml
key: "nginx-ingress"
operator: Exists
```

both of these do not work, but a `matchLabel` works:
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-allow
  namespace: search
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              nginx-ingress: "true"
      ports:
        - port: 3000
  podSelector: {}
  policyTypes:
    - Ingress
```

**Comment by KarstenSiemer** [comment]
We can also report that this is faulty.
Noticed by migrating to calico, all of a sudden we had to change the netpols

**Comment by aauren** [comment]
Closed via #881. Please re-open if you still have issues after trying the latest. Thanks again @filintod!

**Comment by mattlqx** [comment]
There's still a `matchExpressions` selector that doesn't work.

This does not:
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: app-stack
  name: service-allow
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: service
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  - app-stack
```

But changing the selector to (the namespace having this label of course) works:
```
        - namespaceSelector:
            matchLabels:
              app: service
```

The behavior changed at some point after 1.0.0-rc1 as I was running that before upgrading to 1.0.0. After upgrade, my pods that were subject to these NetworkPolicies could no longer reach each other (connection refused). It could be the pull that fixed this original issue caused this selector to stop working?

**Comment by aauren** [comment]
@mattlqx can you show your pod listing with labels and your iptables chain for this pod on a node that contains this pod?

**Comment by filintod** [comment]
@mattlqx one thing to remember is that in network policies you are always matching against labels (not resource names), check the API here https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#networkpolicypeer-v1-networking-k8s-io, so on the top you are selecting namespaces whose label is `name` and value is `app-stack`, I guess you thought this would select by the name of the namespace but all selections are done against labels (matchExpressions and matchLabels), the matchExpression just give you more [set-like operations](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements) not possible with the simpler matchLabels but it is always against labels.  To test a comparable, but more verbose, operation you can do:
```
- namespaceSelector:
    matchExpressions:
     - key: app
       operator: In
       values:
       - service
```

On this netpol in particular if the pods are in the same namespace this netpol is, you actually can do a simpler:
```
ingress:
- ports: [port: 443]
  from:
  -  podSelector: {} # meaning all pods in current namespace
```
