### ISSUE TITLE
Network policy order produces unexpected results

### ISSUE THREAD

**Issue by tomecho** [cloudnativelabs/kube-router#698]
When writing network policies the order of the policy types block matters but it shouldnt

this policy works as expected and allows 1433 outward and 9400 inward
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-policy
  namespace: sso-staging
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 1433
  ingress:
  - ports:
    - protocol: TCP
      port: 9400
```

this policy does not work and denies 1433 outbound traffic
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-policy
  namespace: sso-staging
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
  - Egress  
  - Ingress
  egress:
  - ports:
    - protocol: TCP
      port: 1433
  ingress:
  - ports:
    - protocol: TCP
      port: 9400
```
