### ISSUE TITLE
kube-router sometimes healthz timeout ( may relate to host network )

### ISSUE THREAD

**Issue by chinglinwen** [cloudnativelabs/kube-router#726]
kube-router got timeout warning( on all nodes) several times a day

```
Liveness probe failed: Get http://172.31.81.111:20244/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
```

according to this article

https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02

I've re-produce it with

both run at the same k8s node ( 172.31.81.115 ), the test can be easily re-produce same issue on other k8s nodes

```
./fileserver2 
./snat-race-conn-test -u http://172.31.81.115:9001 -t 3000 -p 3
```

```
2019-04-30 18:25:44 | error |   3000ms | Get http://172.31.81.115:8000?3126769402619748727: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2019-04-30 18:25:44 | error |   3000ms | Get http://172.31.81.115:8000?1891322259007995710: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

https://github.com/maxlaverse/snat-race-conn-test
https://github.com/chinglinwen/fileserver2

**the issue can both happen for kube-router healthz and standalone running service ( on kube-router installed machine )**

**non-kube-router installed machine does not have this problem ( test client is a non-kube-router-installed machine )**

I've also tried test on 116 too, by removing all sysctl configuration, restore it to default, and test again, it still happens

```
// restore to default by empty contents of this file 
[root@online-node-81-116 ~]# cat /etc/sysctl.conf  
# sysctl settings are defined through files in
# /usr/lib/sysctl.d/, /run/sysctl.d/, and /etc/sysctl.d/.
#
# Vendors settings live in /usr/lib/sysctl.d/.
# To override a whole file, create a new file with the same in
# /etc/sysctl.d/ and put new settings there. To override
# only specific settings, add a file with a lexically later
# name in /etc/sysctl.d/ and put new settings there.
#
# For more information, see sysctl.conf(5) and sysctl.d(5).
# Auto-enabled by xs-tools:install.sh
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_mem = 94500000 915000000 927000000
net.ipv4.tcp_max_syn_backlog = 819200
net.ipv4.tcp_max_orphans = 3276800
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_fin_timeout = 30
net.ipv4.ip_local_port_range = 1024  65535
net.ipv4.ip_forward = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
net.core.wmem_max = 16777216
net.core.wmem_default = 8388608
net.core.somaxconn = 32768
net.core.rmem_max = 16777216
net.core.rmem_default = 8388608
net.core.netdev_max_backlog = 32768
kernel.sysrq = 0
kernel.shmmax = 4294967295
kernel.shmall = 268435456
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.core_uses_pid = 1
fs.file-max = 655350
net.ipv4.tcp_max_tw_buckets = 655350

```

## running test from 234 ( no kube-router installed )  --ok 

there's no timeout

## test against service, or service (node-port)  -- ok

there's no timeout

## kube-router.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-router-cfg
  namespace: kube-system
  labels:
    tier: node
    k8s-app: kube-router
data:
  cni-conf.json: |
    {
       "cniVersion":"0.3.0",
       "name":"mynet",
       "plugins":[
          {
             "name":"kubernetes",
             "type":"bridge",
             "bridge":"kube-bridge",
             "isDefaultGateway":true,
             "forceAddress": true,
             "ipam":{
                "type":"host-local"
             }
          }
       ]
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  updateStrategy:
    # type: "RollingUpdate"
    type: "OnDelete"  # manual delete to make effect
  template:
    metadata:
      labels:
        k8s-app: kube-router
        tier: node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: kube-router
      serviceAccount: kube-router
      containers:
      - name: kube-router
        image: harbor.haodai.net/k8s/kube-router:v0.3.0
        imagePullPolicy: Always
        args:
        - --run-router=true
        # - --run-firewall=true
        - --run-service-proxy=true
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - --metrics-port=10270
        - --v=3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_ROUTER_CNI_CONF_FILE
          value: /etc/cni/net.d/10-kuberouter.conflist
        livenessProbe:
          httpGet:
            path: /healthz
            port: 20244
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 5
          # our current liveness may not correct, change threshold to not that sensitive
          failureThreshold: 10
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d
        - name: kubeconfig
          mountPath: /var/lib/kube-router
          readOnly: true
      initContainers:
      - name: install-cni
        image: busybox
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - set -e -x;
          if [ ! -f /etc/cni/net.d/10-kuberouter.conflist ]; then
            if [ -f /etc/cni/net.d/*.conf ]; then
              rm -f /etc/cni/net.d/*.conf;
            fi;
            TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
            cp /etc/kube-router/cni-conf.json ${TMP};
            mv ${TMP} /etc/cni/net.d/10-kuberouter.conflist;
          fi
        volumeMounts:
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d
        - name: kube-router-cfg
          mountPath: /etc/kube-router
      hostNetwork: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: cni-conf-dir
        hostPath:
          path: /etc/cni/net.d
      - name: kube-router-cfg
        configMap:
          name: kube-router-cfg
      - name: kubeconfig
        configMap:
          name: kube-proxy
          items:
          - key: kubeconfig.conf
            path: kubeconfig
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-router
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-router
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - nodes
      - endpoints
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - extensions
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-router
subjects:
- kind: ServiceAccount
  name: kube-router
  namespace: kube-system
# for prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: kube-router
  namespace: kube-system
  labels:
    k8s-app: kube-router
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 10270
    protocol: TCP
  selector:
    k8s-app: kube-router
```

## version
kube-router:v0.3.0
k8s: v1.14
[root@online-node-81-115 ~]# uname -a
Linux online-node-81-115 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
  //other nodes are the same config
