### ISSUE TITLE
GA network policy does not reject if there is not a single source pod matching a policy

### ISSUE THREAD

**Issue by lorenz** [cloudnativelabs/kube-router#85]
Version: c85e02a (current master)

How to reproduce:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
spec:
  podSelector:
    matchLabels:
      np-test: protected
  ingress:
    - from:
      - podSelector:
          matchLabels:
            np-test: allowed
      ports:
      - protocol: TCP
        port: 80
```

1. Run a pod (like nginx) with `np-test: protected`
2. Run a pod (something like busybox:musl) with `np-test: allowed` which which can successfully access the server
3. Run a pod without any labels which cannot access the server
4. Remove the `np-test: allowed` pod
5. Now the unlabeled pod can access the server

In iptables it seems like the issue is that on the network policy chain the source filter is dropped when there are no sources which fails open and not closed.
