### ISSUE TITLE
Kube-router shouldn't rely on kube-proxy configmap

### ISSUE THREAD

**Issue by kvaps** [cloudnativelabs/kube-router#859]
Hi, this PR https://github.com/kubernetes/kubernetes/pull/89593 introduces the important change to provide seamless an upgrade for a cluster using kubeadm and without risks having kube-proxy installed again, but it is rely on missing kube-proxy config.

Problem is that `kube-router` deployed as service-proxy rely on this kube-proxy config:

https://github.com/cloudnativelabs/kube-router/blob/5c5dc411232495f11f6292fb9e4168ae6e228047/daemonset/kubeadm-kuberouter-all-features.yaml#L53-L57
https://github.com/cloudnativelabs/kube-router/blob/5c5dc411232495f11f6292fb9e4168ae6e228047/daemonset/kubeadm-kuberouter-all-features.yaml#L83-L84
https://github.com/cloudnativelabs/kube-router/blob/5c5dc411232495f11f6292fb9e4168ae6e228047/daemonset/kubeadm-kuberouter-all-features.yaml#L127-L132

**Comment by murali-reddy** [comment]
related https://github.com/cloudnativelabs/kube-router/issues/833

**Comment by jcpuzic** [comment]
Came to say doing this fixed an issue in k8s v1.17.2 where kube-router was trying to connect to the cluster IP for the API.  Using the manifest above, I can confirm this it is good.

**Comment by aauren** [comment]
Adding to this that we should also update our documentation (as proposed in #833) to show how to install kube-router using kubeadm without utilizing kube-proxy once we get the configmap sorted.

**Comment by asteven** [comment]
> Came to say doing this fixed an issue in k8s v1.17.2 where kube-router was trying to connect to the cluster IP for the API. Using the manifest above, I can confirm this it is good.

This is exactly the problem.

The default kubeconfig that the pod gets when not (ab)using the one from kube-proxy is pointing at the cluster IP to talk to the API server. But when not using kube-proxy, kube-router is the one who actually makes cluster IPs work in the first place. Classical chicken vs egg problem.

The difference with the kube-proxy provided kubeconfig vs the default one is that it directly uses the API servers IP (aka  controlPlaneEndpoint in kubeadm) without going through the cluster IP.

In my cluster there is a cluster-info config map that contains the controlPlaneEndpoint IP.
Maybe that could be used to generate a working kubeconfig for kube-router?
But not sure if that CM exists in any possible/supported cluster.

```
kubectl -n kube-public get cm cluster-info -o yaml
```

**Comment by aauren** [comment]
I agree that this is a problem. kube-router should not be relying on a config from another component (especially one that it is often meant to replace) in order to function correctly.

@asteven that cluster-info config map is a good find! However, it's in the wrong namespace. Thinking it through I thought that we could use a hyperkube initContainer to copy it over to the kube-system namespace, but it starts to feel really hacky really fast. In the end I wonder if we'll end up in the same space as before, where we're "borrowing" someone else's config and trying to make it work for us.

I think in the end, it is correct for kube-router to assume that this configmap is provided for us. I think that the best way forward would be if kubeadm could provide our config for us the same way it does for other addon elements like kube-proxy and coredns. However, I'm not super familiar with kubeadm. Looking through their docs quickly I didn't see a lot of information about extending kubeadm, or adapting it to other proxy providers.

Does anyone in this thread have any information about how we could potentially configure or customize kubeadm to provide us this config in a way that doesn't rely on kube-proxy?

**Comment by asteven** [comment]
> I think in the end, it is correct for kube-router to assume that this configmap is provided for us. I think that the best way forward would be if kubeadm could provide our config for us the same way it does for other addon elements like kube-proxy and coredns. However, I'm not super familiar with kubeadm. Looking through their docs quickly I didn't see a lot of information about extending kubeadm, or adapting it to other proxy providers.

Unfortunately that is not going to happen. Upstream does not want kubeadm to know any details about addons. They will not add something just for kube-router.


But I think I found something that gives us what we need and that exists on every kubernetes node.

/etc/kubernetes/kubelet.conf

If we mount that as a volume we can run something like this on startup:

```
api_server="$(awk '/server: / {print $2}'  /etc/kubernetes/kubelet.conf)"

cat > /var/lib/kube-router/kubeconfig << DONE
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: ${api_server}
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
DONE
```
