### ISSUE TITLE
Egress network policies should not be applied to pod to service VIP traffic

### ISSUE THREAD

**Issue by aauren** [cloudnativelabs/kube-router#905]
When we merged #891 it also had an unintended effect of making it so that you have to specify both the pod IPs / selectors AND the externalIP / ClusterIP in the network policy.

As an example:
Given that we run CoreDNS it has a pod IP of `172.31.2.181` and a ClusterIP of `172.28.0.10`

If I apply the following policy:
```
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: coredns
```
(assume that those selectors are correct for targeting CoreDNS)

Then go into a pod and try to connect to CoreDNS via the ClusterIP (as most stuff does):
```
# nslookup google.com 172.28.0.10
;; connection timed out; no servers could be reached
```

Now if instead of targeting the ClusterIP, I target the Pod:
```
# nslookup google.com 172.31.2.181
Server:         172.31.2.181
Address:        172.31.2.181#53
Non-authoritative answer:
Name:   google.com
Address: 172.217.14.78
Name:   google.com
Address: 2607:f8b0:4007:80e::200e
```
So it works as long as you specify it by the Pod IP and not the Cluster IP

If I then edit the policy to contain:
```
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: coredns
  - ports:
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 172.28.0.10/32
```
Then go back into a pod, now everything works:
```
# nslookup google.com 172.28.0.10
Server:         172.28.0.10
Address:        172.28.0.10#53
Non-authoritative answer:
Name:   google.com
Address: 172.217.14.110
Name:   google.com
Address: 2607:f8b0:4007:80e::200e
```
