### ISSUE TITLE
NPC's new synchronization refreshes the ipsets that are still in use by the current iptables rules

### ISSUE THREAD

**Issue by jimmy-zh** [cloudnativelabs/kube-router#949]
The ipsets used in NPC are named based on certain constant factors, which will cause a new synchronization to refresh the ipsets that are still in use by the current iptables rules. We need to isolate the ipsets used by different synchronizations to ensure consistency.

**Comment by aauren** [comment]
@jimmy-zh Can you give more details about the problem you're seeing and why the isolation is needed?

For instance, with an ipset that contains all of the pod IPs for a selector I would expect to be consistent. If a new pod is created that matches that selector, the ipset and it's references should stay the same given that it still represents the same pod, only the new pod IP should be added.

Adding version to the ipset hashing is going to create a lot of churn which will make debugging harder and potentially increase load on the system.

**Comment by jimmy-zh** [comment]
@aauren OK. Suppose we have such a networkpolicy object:
```
spec:
  egress:
  - ports:
    - port: 8090
    to:
    - ipBlock:
        cidr: 10.13.0.0/16
  podSelector:
    matchLabels:
      run: client
```
The iptables rule generated on the node will look like this:
```
-A KUBE-NWPLCY-QE4UGEOFQIWFIMJO -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to specified ipBlocks selected by policy name: test namespace default" -m set --match-set KUBE-SRC-TYQOJEEGIEW3MM26 src -m set --match-set KUBE-DST-GADOPVUH5KBJ4I3Z dst -m tcp --dport 8090 -m comment --comment "rule to RETURN traffic matching a network policy" -m mark --mark 0x10000/0x10000 -j RETURN
```
This rule allows traffic from `client pods(KUBE-SRC-TYQOJEEGIEW3MM26)` to `10.13.0.0/16:8090(KUBE-DST-GADOPVUH5KBJ4I3Z)`. If we update the networkpolicy object as follows:
```
spec:
  egress:
  - ports:
    - port: 8090
    to:
    - ipBlock:
        cidr: 10.14.0.0/16
  podSelector:
    matchLabels:
      run: server
```

A new synchronization will be triggered. First, the ipset `KUBE-SRC-TYQOJEEGIEW3MM26` is refreshed to the server pods, and before the ipset `KUBE-DST-GADOPVUH5KBJ4I3Z` is refreshed to `10.14.0.0/16`, the iptables rule is in intermediate state, which will allow traffic from `server pods (KUBE-SRC-TYQOJEEGIEW3MM26)` to `10.13.0.0/16:8090 (KUBE-DST-GADOPVUH5KBJ4I3Z)`. Obviously this is inconsistent.

Therefore, the key point is that if we isolate the iptables chains by version, we should also isolate the ipsets by the same version to ensure consistency.
